### ISSUE TITLE
openvas_lib.common.ClientError: [400] create_task_response: Bogus element: preference

### ISSUE THREAD

**Issue by anandtiwarics** [golismero/openvas_lib#23]
Hi,

I'm trying to launch a scan and getting below error.

```
>>> from openvas_lib import VulnscanManager, VulnscanException
>>> scanner = VulnscanManager("192.168.0.14", "admin", "admin")
>>> scan_id, target_id = scanner.launch_scan(target='192.168.0.14', profile='Full and fast')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openvas_lib/__init__.py", line 657, in launch_scan
    comment=comment)
  File "openvas_lib/ompv7.py", line 715, in create_task
    return self._manager.make_xml_request(request, xml_result=True).get("id")
  File "openvas_lib/common.py", line 389, in make_xml_request
    response.get('status_text')))
openvas_lib.common.ClientError: [400] create_task_response: Bogus element: preference
```

Thanks.

**Comment by smitty0421** [comment]
I am having the same problem.

Thanks,
Steve

**Comment by marryfaye** [comment]
me too

**Comment by marryfaye** [comment]
I am having the same problem in kali3.0 and openvas7.0.2

**Comment by anandtiwarics** [comment]
Thanks, it's working now.

**Comment by anandtiwarics** [comment]
Hi @MarioVilas 

Is it possible to update https://pypi.org/project/openvas_lib/ too? 

Thanks.

**Comment by MarioVilas** [comment]
I don't have access to it. /cc @cr0hn

**Comment by cr0hn** [comment]
I just added continuous integration cycle with auto-upload to Pypi the new pull-request. 

It was uploaded to Pypi with version: 1.1.3.

Please, test it and feedback if something was wrong. 

Thx!

**Comment by anandtiwarics** [comment]
Hi @cr0hn,

I've verified and it has not been updated. I think you should upload with the newer version as 1.1.3 already there.

Thanks.

**Comment by cr0hn** [comment]
Ups, sorry. Just submitted version 1.1.4

**Comment by anandtiwarics** [comment]
Hi,

version 1.1.4 uploaded but something broken after installing using pip. 

```
>>> from openvas_lib import VulnscanManager, VulnscanException
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named openvas_lib
```

may its not able to map with sit-packages. Could you please review from your end why its not able to import openvas_lib ?

Thanks.

**Comment by anandtiwarics** [comment]
@cr0hn ,

Got the issue. Package missing openvas_lib folder https://pypi.org/project/openvas_lib/1.1.4/#files

Please upload with the openvas_lib folder in the package.

**Comment by cr0hn** [comment]
I just fixed the issue. I was an error in the setup. In my machine now I can import the library. Please, check and feedback me

**Comment by anandtiwarics** [comment]
Perfect. Work like a charm. Thanks @cr0hn
