### ISSUE TITLE
[!] OpenVAS: Plugin disabled, reason: Error while connecting to the server: [Errno -3] Temporary failure in name resolution. when i try to connecty server this error occur anybody know any solution.

### ISSUE THREAD

**Issue by sanghinitin** [golismero/openvas_lib#5]

**Comment by MarioVilas** [comment]
I would say the plugin configuration is wrong. Check that you can actually
access the server and it's a supported version. :)

On Tuesday, July 7, 2015, NITIN SANGHI <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/golismero/openvas_lib/issues/5>.
>


-- 
“There's a reason we separate military and the police: one fights the enemy
of the state, the other serves and protects the people. When the military
becomes both, then the enemies of the state tend to become the people.”
